opt_in_rules:
    - closure_spacing
    - empty_count
    - fatal_error_message
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prohibited_super_call
    - vertical_parameter_alignment_on_call
    
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    
disabled_rules:
    - trailing_whitespace
    - identifier_name
    - nesting
    - file_length
    - type_body_length
    - function_body_length
    - trailing_comma
    - cyclomatic_complexity

included:
    - ImageUI-Demo
    - ../Sources/ImageUI
